package com.models;
// Generated 25/10/2017 01:07:16 AM by Hibernate Tools 4.3.1



/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {


     private Integer codE;
     private String nombres;
     private String apellidos;
     private char sexo;

    public Empleado() {
    }

    public Empleado(String nombres, String apellidos, char sexo) {
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.sexo = sexo;
    }
   
    public Integer getCodE() {
        return this.codE;
    }
    
    public void setCodE(Integer codE) {
        this.codE = codE;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public char getSexo() {
        return this.sexo;
    }
    
    public void setSexo(char sexo) {
        this.sexo = sexo;
    }




}


